### ISSUE TITLE
图片编辑后，新的图片大小暴增

### ISSUE THREAD

**Issue by lionsom** [longitachi/ZLImageEditor#1]
问题1：编辑前图片是7M，编辑后图片大小是23M，放大了好几倍。
问题2：选择图片后，点击编辑按钮，选择某一个功能准备编辑，但是没有实际的编辑操作，直接点击完成后，图片也算编辑后了的，导致新图片大小也暴增了。

**Comment by longitachi** [comment]
我这边试了下相册里的图片编辑时候不会取原图，一般3M多的，编辑完是4M左右，确实大了，我后面看下。
第二个问题，没有实际编辑操作我测试的是不会算编辑的

**Comment by longitachi** [comment]
看错repo了。以为是相册选择的那个，相册选择的那个编辑有更新，没有实际操作不算编辑，这个库等有空了我更新下
