### ISSUE TITLE
I am getting a crash on Done button after editing the image

### ISSUE THREAD

**Issue by app-arianamini** [longitachi/ZLImageEditor#11]
`        error = vImageScale_ARGB8888(&sourceBuffer, &destBuffer, nil, numericCast(kvImageHighQualityResampling))`

Unfortunately, I am unable to give more information, it happens with XCode 13.3 and iOS 15.4. 
![Screenshot 2022-03-21 at 11 12 43](https://user-images.githubusercontent.com/36501919/159241232-3028f588-feb7-4f11-9475-f9e6b5d9d576.png)
![Screenshot 2022-03-21 at 11 12 58](https://user-images.githubusercontent.com/36501919/159241273-7450b3aa-2061-46e9-a729-89ac5643e54f.png)

Why are we using over **400 MB RAM** by editing just 3 Images?

**Comment by app-arianamini** [comment]
Okay, I found out, that if I press on Save button (after drawing on an Image), the memory usage increase instantly from 100 to 400 and its crashes.

**Comment by longitachi** [comment]
Sorry, I can't fix this crash right now, you can disable the code that caused the crash first.

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLImageEditor/blob/8e5437c20d5ecbb516ee028e1c994518747bbcc9/Sources/General/ZLEditImageViewController.swift#L816-L820

**Comment by longitachi** [comment]
@app-arianamini  Can you upload the image that caused this crash.

**Comment by app-arianamini** [comment]
Thanks, but I thought this resizing might be more important, probably need to add a little more comments.

**Comment by longitachi** [comment]
Upgrade to 1.0.6, use jpegData(compressionQuality:) to compress images.

**Comment by kockok** [comment]
Sometimes the screen is freezes after hitting the 'done' button, I would suggest to create a loading state after tapping the 'done' button.

**Comment by longitachi** [comment]
OK, I'll add it in the next version.
