### ISSUE TITLE
Support custom ZLEditImageViewController

### ISSUE THREAD

**Issue by hoangnam714** [longitachi/ZLImageEditor#18]
Hi, 
I have an interface like this
<img width="243" alt="Screen Shot 2022-05-13 at 10 58 23" src="https://user-images.githubusercontent.com/51524705/168208755-80831739-097e-4e58-b104-670f56a540a9.png">
Can I customize something for ZLEditImageViewController, background can't be zoomed and cropped, allows adding images from phone gallery instead of existing emojis

**Comment by hoangnam714** [comment]
I hope you can release a new version soon, for now can I use your code for commercial application, I need to edit the included toolkit

**Comment by hoangnam714** [comment]
@longitachi Do you can exchange quickly through applications such as slack, message, whatapp,...

**Comment by longitachi** [comment]
slack: zl495181165@gmail.com

**Comment by hoangnam714** [comment]
Can you accept my invitation to join my workspace, I have some questions

**Comment by longitachi** [comment]
> Can you accept my invitation to join my workspace, I have some questions

No, here is my whatsapp id: longitachi

**Comment by shadzik** [comment]
The license is MIT, so you can use this software in commercial applications.

**Comment by hoangnam714** [comment]
Thank you for your help, I hope to be able to contribute something in the future
ZLImageEditor

**Comment by hoangnam714** [comment]
oh no, can you support ZLEditImageViewController to UIVIew so I can embed into another viewcotroller, this makes it easier to customize ui of ZLEditImageViewController, currently I can only present ZLEditImageViewController @longitachi

**Comment by shadzik** [comment]
You could instatiate the VC and use it's view property to embed in another VC as child or so...

**Comment by hoangnam714** [comment]
@shadzik
<img width="927" alt="Screen Shot 2022-05-15 at 21 29 25" src="https://user-images.githubusercontent.com/51524705/168478066-3eac6197-2c1f-478c-b61e-2683172d390e.png">
Looks like @longitachi  forgot to publicize the ZLEditImageViewController constructor, so I can't do it the way you suggested.

**Comment by shadzik** [comment]
Yes, you're right, for the time being you could just make the init method public.

**Comment by longitachi** [comment]
> @shadzik <img alt="Screen Shot 2022-05-15 at 21 29 25" width="927" src="https://user-images.githubusercontent.com/51524705/168478066-3eac6197-2c1f-478c-b61e-2683172d390e.png"> Looks like @longitachi forgot to publicize the ZLEditImageViewController constructor, so I can't do it the way you suggested.

1.1.1 fixed

**Comment by hoangnam714** [comment]
that's right you can create a delegate func addImageStickerView, addTextStickersView so that anyone can create a screen to select their favorite image like this for example
![IMG_159C057337B7-1](https://user-images.githubusercontent.com/51524705/168512758-af690509-6eb9-494d-96df-9434b58954f1.jpeg)
it would be great if you support this too, thank you so much

**Comment by longitachi** [comment]
You can do it like this
```swift
class ImageStickerContainerView: UIView, ZLImageStickerContainerDelegate {

    func show(in view: UIView) {
        let vc = ImageStickerViewController()
        vc.hideBlock = { [weak self] in
            self?.hide()
        }
        getTopViewController()?.showDetailViewController(vc, sender: nil)
    }

}


class ImageStickerViewController: UIViewController {

    var hideBlock: (() -> Void)?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        // Do any additional setup after loading the view.
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        hideBlock?()
    }
    
}
```

**Comment by hoangnam714** [comment]
Ohno... @longitachi 
I see some of the following problems:
- bottomShadowView in ZLEditImageViewController.swift:485 is I think it's not needed, it causes error when hiding bottomShadowView
- how can i scale to fill my image with mainScrollView, i use public parameter version 1.1.1 but it doesn't work, the image i included has black background
![IMG_BAA9112290F7-1](https://user-images.githubusercontent.com/51524705/168523154-0a4359cd-0702-44d8-b475-79c34036e87b.jpeg)

**Comment by longitachi** [comment]
I think it would be better if you fork this repo and then add the custom features you need...

**Comment by hoangnam714** [comment]
@longitachi Thank you for your help,
<img width="299" alt="Screen Shot 2022-05-18 at 10 19 27" src="https://user-images.githubusercontent.com/51524705/168950347-0de18117-cff5-4d58-914d-f707bbd6cd23.png">

I tried with some code and found the following code works quite well, but I am confused when applying this code to ZLImageStickerView pangeture and ZLTextStickerView, can you help me. Below is the support code

    ```
@objc func handlePan(_ gesture: UIPanGestureRecognizer) {
        
        let translation = gesture.translation(in: _Container_image_view)
        guard let gestureView = gesture.view else {
            return
        }
        gestureView.center = CGPoint(
            x: gestureView.center.x + translation.x,
            y: gestureView.center.y + translation.y
        )
        gesture.setTranslation(.zero, in: _Container_image_view)
        
        guard gesture.state == .ended else {
            return
        }
        let velocity = gesture.velocity(in: _Container_image_view)
        let magnitude = sqrt((velocity.x * velocity.x) + (velocity.y * velocity.y))
        let slideMultiplier = magnitude / 200
        let slideFactor = 0.1 * slideMultiplier
        var finalPoint = CGPoint(
            x: gestureView.center.x + (velocity.x * slideFactor),
            y: gestureView.center.y + (velocity.y * slideFactor)
        )
        finalPoint.x = min(max(finalPoint.x, 0), _Container_image_view.bounds.width)
        finalPoint.y = min(max(finalPoint.y, 0), _Container_image_view.bounds.height)
        UIView.animate(
            withDuration: Double(slideFactor * 2),
            delay: 0,
            options: .curveEaseOut,
            animations: {
                gestureView.center = finalPoint
            })
    } 
```

**Comment by longitachi** [comment]
Sorry, I don't understand your question. What does this code do?

**Comment by hoangnam714** [comment]
this code works as keep the imagesticker always inside the viewcontainer

https://user-images.githubusercontent.com/51524705/168974559-0bfcb236-0125-44d2-bac6-e188fb9665d7.mp4

**Comment by hoangnam714** [comment]
I sent a message to whatsapp, did you receive it, I think it will be easier to communicate there
