### ISSUE TITLE
编辑之后图片失真严重

### ISSUE THREAD

**Issue by gu0315** [longitachi/ZLImageEditor#2]

**Comment by gu0315** [comment]
多次编辑之后

**Comment by longitachi** [comment]
这是上次更新的一个问题 https://github.com/longitachi/ZLImageEditor/blob/871ae929203d6c92799ce071b6f5598ae58bc0f5/Sources/General/ZLEditImageViewController.swift#L681-L683 编辑后图片会变大，想着压缩一下，结果造成压缩过渡了，如果着急需要修改，可先删除这几行压缩代码。之后在考虑新方案吧

**Comment by gu0315** [comment]
好的,多谢
