### ISSUE TITLE
请问如何选中图片后强制crop

### ISSUE THREAD

**Issue by hstdt** [longitachi/ZLImageEditor#20]
目前设置`clipRatios`需要用户手动进入编辑状态才能生效，请问如何类似于twitter选择背景那样，强制图片的比例呢?

ps: crop之后，文字如果拖动到crop范围之外，就无法拖回来了。

**Comment by hstdt** [comment]
比如选择完毕图片之后要先进入crop才能进行下一步操作，之后无法再次crop

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLPhotoBrowser/issues/729

**Comment by longitachi** [comment]
```swift
ZLImageEditorConfiguration.default()
    .showClipDirectlyIfOnlyHasClipTool(true)
    .editImageTools([.clip])
    .clipRatios([.wh1x1])
```
这样设置即可

**Comment by hstdt** [comment]
非常感谢~

**Comment by hstdt** [comment]
@longitachi 
如果是gif图，ZLPhotoBrowser可以选择跳过裁剪么

**Comment by longitachi** [comment]
Gif图不支持编辑

**Comment by hstdt** [comment]
@longitachi  但是如果设置`showClipDirectlyIfOnlyHasClipTool`为true的话，会强制进行裁剪。如果是gif的话，能跳过这个判断么，或者把`showClipDirectlyIfOnlyHasClipTool`作为block。目前效果是会强制裁剪gif(使用ZLPhotoBrowser而不是直接使用ZLImageEditor，中间没有可以接入的抓手block)

**Comment by hstdt** [comment]
另外在这个场景下，`showClipDirectlyIfOnlyHasClipTool`为true会导致`canSelectAsset`和`operateBeforeDoneAction`不会被调用(因为这两个触发是在确定按钮上)

```
let editImageConfiguration = ZLPhotoConfiguration.default().editImageConfiguration
editImageConfiguration
    .tools([.clip])
    .clipRatios([.wh1x1])

ZLPhotoConfiguration.default()
    .editImageConfiguration(editImageConfiguration)
    .navCancelButtonStyle(.image)
    .editAfterSelectThumbnailImage(true) --->  导致canSelectAsset和operateBeforeDoneAction不被调用，会比如无法控制图片大小
    .showClipDirectlyIfOnlyHasClipTool(true)   ---> 强制裁剪了gif
    .allowSelectImage(true)
    .allowSelectVideo(false)
    .maxSelectCount(1)
    .showCaptureImageOnTakePhotoBtn(false)
    .canSelectAsset { phsset in
        // Not Called
    }
    .operateBeforeDoneAction { vc, action in
        // Not Called
        action()
    }
```

**Comment by longitachi** [comment]
等有空了我看下，最近比较忙

**Comment by hstdt** [comment]
@longitachi 
如果提`pull request`的话，选择gif的时候，更倾向于把`showClipDirectlyIfOnlyHasClipTool`增加一个block开放给用户，还是判断UIImage是否是GIF?

![CleanShot 2022-06-23 at 10 53 31](https://user-images.githubusercontent.com/10215098/175197127-1d0620ea-2740-4d5f-8bf9-c1b4501ab68e.png)

**Comment by longitachi** [comment]
不提供block，判断类型

**Comment by hstdt** [comment]
@longitachi 
按照这个思路写了一下，发现如果有需求就是允许裁剪gif的第一张图，然后拿来用，判断model/UIImage的类型就会有问题。这个是不是只能交给使用者实时来判断。

**Comment by hstdt** [comment]
一个不完美的workaround思路

设置`saveNewImageAfterEdit`为false，然后在`selectImageBlock`中重新通过asset将原始gif图读取出来。
