### ISSUE TITLE
Can you update edit with undo and redo 

### ISSUE THREAD

**Issue by TruongMinhThuan** [longitachi/ZLImageEditor#23]
Hi,
Thanks for your great works.
Can you update on IOS with undo and redo like below image.
![IMG_1633](https://user-images.githubusercontent.com/89587992/186399350-0d102f36-dd14-4d49-b8a5-5b0967c3c4a9.jpg)

**Comment by longitachi** [comment]
Version 1.1.2 already supports this feature.
