### ISSUE TITLE
center text

### ISSUE THREAD

**Issue by fukemy** [longitachi/ZLImageEditor#4]
hi, thanks for great lib, i want to put text in center like facebook, did u support this? Thanks

**Comment by longitachi** [comment]
![image](https://user-images.githubusercontent.com/11711768/130383249-ef1d1dcc-eaba-4018-b316-603092c38e10.png)
Like this? this feature is not yet supported.

**Comment by fukemy** [comment]
yes, thanks. waiting for new feature bro
