### ISSUE TITLE
请问如何自定义编辑器上按钮的文字

### ISSUE THREAD

**Issue by wdq123550** [longitachi/ZLImageEditor#43]
比如完成、饱和度那些

**Comment by wdq123550** [comment]
![image](https://user-images.githubusercontent.com/20955893/234452145-d2cbe57f-3246-4f2c-bca1-bbe626badd41.png)
我们App里有在App内选择语言的功能，导致App内语言和系统语言可以不一致，这个库的语言貌似是跟随系统的，我除了自定义按钮上的文字，还有其他办法让库的语言跟随App而不跟随系统吗？

**Comment by wdq123550** [comment]
或者说有什么方法可以在editController present之前设置，让库显示对应的语言之类的。(读取我们App的当前语言，设置库，让库显示对应的语言)

**Comment by wdq123550** [comment]
另外问一句，貌似没有图片贴纸的功能了？

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLImageEditor/blob/master/Sources/General/ZLImageEditorUIConfiguration.swift

注释都有
