### ISSUE TITLE
请问是否有某个属性标明，图片是否被编辑过

### ISSUE THREAD

**Issue by wdq123550** [longitachi/ZLImageEditor#44]
在一次编辑的周期中，有什么能标明，图片是否被修改或者编辑过。然后可以一键恢复原图那种

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLImageEditor/blob/b0fe011dc9db2f64578393f2c5cd77aaf132a747/Sources/General/ZLEditImageViewController.swift#L322-L328
会返回给调用方一个`ZLEditModel`对象，可判断这个对象是否为空作为是否编辑过的依据。编辑器内不能一键恢复原图

**Comment by wdq123550** [comment]
如果不是调用这个方法，而是自己创建VC，自己PUSH的呢？

**Comment by longitachi** [comment]
> 如果不是调用这个方法，而是自己创建VC，自己PUSH的呢？

没明白你的意思。编辑图片不论你外面怎么套，最后不都得调用这个方法。
