### ISSUE TITLE
how to change text sticker background 

### ISSUE THREAD

**Issue by heshesh2010** [longitachi/ZLImageEditor#46]

**Comment by longitachi** [comment]
This feature is not supported now.

**Comment by longitachi** [comment]
This feature is supported in v1.1.8.

![Simulator Screen Shot - iPhone 14 Pro - 2023-07-21 at 16 36 15](https://github.com/longitachi/ZLImageEditor/assets/11711768/d740c03d-1fe8-42da-856e-3592fa19e7d3)
