### ISSUE TITLE
text sticker not showing after hit done button

### ISSUE THREAD

**Issue by heshesh2010** [longitachi/ZLImageEditor#48]
Hi , using latest update , when I use text sticker and user hit done button I found it gets empty box without text and sometimes it shows part of the text , 

but when I sent background to text and remove the background again , it fully shows 

" pls not this only happen when I type arabic , and English is working " 
screen shot 

note : I was set red circle to show u the empty text box 

![Screenshot 2023-10-10 at 7 34 19 PM](https://github.com/longitachi/ZLImageEditor/assets/16393042/a364ce76-99e8-4fdb-8566-1b72ec574fd9)

**Comment by longitachi** [comment]
If your iPhone region is Arabic, you can set `ZLImageEditorUIConfiguration.default().languageType = .system`, otherwise set `ZLImageEditorUIConfiguration.default().languageType = .arabic` to avoid this problem!

But when your iPhone region is non-Arabic, there will be a bug if you input Arabic, this issue will be fixed later!

**Comment by heshesh2010** [comment]
> If your iPhone region is Arabic, you can set `ZLImageEditorUIConfiguration.default().languageType = .system`, otherwise set `ZLImageEditorUIConfiguration.default().languageType = .arabic` to avoid this problem.
> 
> But when your iPhone region is non-Arabic, there will be a bug if you input Arabic, this issue will be fixed later.

@longitachi ok I'm waiting your fix as soon as possible , 

I want to ask u how to change default font to custom font in text sticker , I was trying to add font to Xcode main project and in plist file also and in your pod as private var font = UIFont(name: "IBMPlexSansArabic", size: 18) ?? UIFont.systemFont(ofSize: 18) 

in ZLInputTextViewController file , but seems not reading it

**Comment by longitachi** [comment]
Use `fontChooserContainerView`. You should provide a view that confirmed the protocol of `ZLTextFontChooserDelegate`. You can refer to the implementation of `FontChooserContainerView` in the demo.

```Swift
ZLImageEditorConfiguration.default().fontChooserContainerView(FontChooserContainerView())
```

**Comment by heshesh2010** [comment]
> Use `fontChooserContainerView`. You should provide a view that confirmed the protocol of `ZLTextFontChooserDelegate`. You can refer to the implementation of `FontChooserContainerView` in the demo.
> 
> ```swift
> ZLImageEditorConfiguration.default().fontChooserContainerView(FontChooserContainerView())
> ```

thanks for your respond , but I use this package as pod in my flutter app project , so I have only source files swift code without full example app so I can't open the ZLImageEditior full project In Xcode .

can u help me to where I can edit the text sticker vars to include my custom front 
<img width="1365" alt="Screenshot 2023-10-12 at 3 36 56 PM" src="https://github.com/longitachi/ZLImageEditor/assets/16393042/263d386f-eac4-4e89-8425-f2514f6b3ad6">
