### ISSUE TITLE
How to change icon in ToolBar ?

### ISSUE THREAD

**Issue by baronha** [longitachi/ZLImageEditor#5]
This is a great library.
But I want to custom Toolbar (change Icon Image, Color when it active, done/close button's style). How to do it?

**Comment by longitachi** [comment]
This library does not support these features. But this library is extracted from [ZLPhotoBrowser](https://github.com/longitachi/ZLPhotoBrowser). So you can use ZLPhotoBrowser instead.

```swift
/// Developers can customize images, but the name of the custom image resource must be consistent with the image name in the replaced bundle.
/// - example: Developers need to replace the selected and unselected image resources, and the array that needs to be passed in is
/// ["zl_btn_selected", "zl_btn_unselected"].
@objc public var customImageNames: [String] = []

/// Color configuration for framework.
@objc public var themeColorDeploy: ZLPhotoThemeColorDeploy = .default()
```

**Comment by baronha** [comment]
Thanks a lot for your answer. I hope to be able to customize the look and feel of the library in the future.
