### ISSUE TITLE
Video support?

### ISSUE THREAD

**Issue by mohsenvp** [longitachi/ZLImageEditor#50]
Does this support video? Do you have a plan for it?

**Comment by longitachi** [comment]
This framework only supports image editing. However, you can utilize the [ZLEditVideoViewController](https://github.com/longitachi/ZLPhotoBrowser/blob/master/Sources/Edit/ZLEditVideoViewController.swift) class in `ZLPhotoBrowser`, although this functionality has not been separately extracted.
