### ISSUE TITLE
Introduce a callback when user presses on cancel button

### ISSUE THREAD

**Issue by hsingh-texada** [longitachi/ZLImageEditor#55]
I am facing an issue where there is no callback when the user presses the cancel button. This results in the UI not getting updated when a cancellation is initiated.

**Comment by hsingh-texada** [comment]
In addition to the selection of the photo in the following code

```
ZLEditImageViewController.showEditImageVC(parentVC: self, image: image, editModel: editModel) { [weak self] (resImage, editModel) in
    // your code
}
```

we should introduce am optional closure, something like 

```
didCancel: {
  // callers implementation
}
```

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLImageEditor/commit/e5ede2810dc39014848c0b4300eb95320b4fcbaf
