### ISSUE TITLE
Auto Scale Text size according to Gesture.

### ISSUE THREAD

**Issue by khushbu147Service** [longitachi/ZLImageEditor#7]
Hello,
Its Great Library for Photo Editing. I want to Increased or decreased size of text font according to Gesture on Box Corner.Can You please provide in your Library.

Thanks in Advanced.

**Comment by longitachi** [comment]
This feature is now supported. You can pinch the text to zoom.

**Comment by khushbu147Service** [comment]
Thanks Buddy
