### ISSUE TITLE
Background color change

### ISSUE THREAD

**Issue by doganoruc** [longitachi/ZLImageEditor#9]
Hello, 
Thank you for your works. I'm using it in iOS application and trying to modify an image with transparent background. However, when it saves the modified image, it saves image with white backgroud. I want to save it with transparent background. Is there any solution for this problem?

Thanks for the support in advance,

**Comment by longitachi** [comment]
![test](https://user-images.githubusercontent.com/11711768/148667022-fedf9136-6d9b-458c-a7fe-4138fc9f5280.gif)
I edited an image with a transparent background, and when I saved it, it was already saved with a transparent background.

**Comment by baronha** [comment]
same issue https://github.com/baronha/react-native-photo-editor/issues/14

**Comment by longitachi** [comment]
> ![test](https://user-images.githubusercontent.com/11711768/148667022-fedf9136-6d9b-458c-a7fe-4138fc9f5280.gif) I edited an image with a transparent background, and when I saved it, it was already saved with a transparent background.
@baronha Look at this GIF image. It does have a transparent background after editing while I'm testing.

**Comment by baronha** [comment]
> 
Oh. You can try with remote image url

**Comment by longitachi** [comment]
https://github.com/longitachi/ZLImageEditor/blob/1077a7a2f85274c4b69e5efb7860e7b897698f0b/Sources/Extensions/UIImage%2BZLImageEditor.swift#L306-L329 The background is changed when compressing.

**Comment by longitachi** [comment]
@doganoruc @baronha The latest version fixes this problem.
